version: 2.1
commands:
  run_test_nodes:
    description: Run docker-compose nodes
    steps:
      - run:
          name: Run nodes in background
          command: docker-compose up
          background: true
      - run:
          name: Give it some time to boot the nodes
          command: sleep 30

  health_check_node:
    description: Health Check a Node
    parameters:
    steps:
      - run:
          name: Health check APIs
          command: ./test/healthcheck.sh

jobs:
  integration_tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run_test_nodes
      - health_check_node

workflows:
  test:
    jobs:
      - integration_tests:
          requires: []
